### ISSUE TITLE
Using with ionic2 or 3

### ISSUE THREAD

**Issue by corsaireplus** [razmans/ionicBluetoothPrint#1]
How can use to print data on bluetooth thermal printer  ?

**Comment by razmans** [comment]
See print provider in the folder 'providers' 
Its very straight forward in that folder.

 You have to first select a printer and connect to it and then send the data to the thermal printer via bluetooth terminal connection.

**Comment by corsaireplus** [comment]
thanks its worked for me ... now how can print barcode or qrcode ?

**Comment by razmans** [comment]
Printing barcode and images is part of my todo list on this repo. Have not been able to get around to do it. If you are able to figure it out, please share. :)

**Comment by teebazz** [comment]
Please can i print HTML content
