### ISSUE TITLE
how to chinese character print

### ISSUE THREAD

**Issue by akmelalee** [razmans/ionicBluetoothPrint#10]

**Comment by blinkuz** [comment]
@akmal305 See [#8](https://github.com/razmans/ionicBluetoothPrint/issues/8)

**Comment by akmelalee** [comment]
Thanks u response!!!!!!!!!!!!
i try

**Comment by akmelalee** [comment]
@blinkuz  i'm not understand this file , please guide me.
how to use this file ?

..
..
import * as iconv from 'iconv-lite';
..
..
let encodedWord = iconv.encode('謝謝', 'EUC-CN');

**Comment by blinkuz** [comment]
@akmal305 I have never done nor have I ever tried it but after investigating a bit the [iconv-lite](https://github.com/ashtuchkin/iconv-lite) is a library that allows you to encode text to buffer and then send it to the printer.

You must do these steps:

1.`npm i iconv-lite` in the console.

2.In your controller ts: `import * as iconv from 'iconv-lite';`.

3.In the method you are creating the format for your print you encode the Chinese characters with this: `let encodedWord = iconv.encode('謝謝', 'EUC-CN');`.

NOTE: The EUC-CN means Extended Unicode which is used in languages such as Japanese, Korean, and Simplified Chinese.

**Comment by akmelalee** [comment]
@blinkuz 
thanks your response !!!!!!
 i try
