### ISSUE TITLE
ZebraPrinter bluethoot CPCL_language ionic

### ISSUE THREAD

**Issue by avarela91** [razmans/ionicBluetoothPrint#17]
Hello, I'm looking for a way to print a receipt on a ZABRA ZQ320 printer from my ionic v3 application using CPCL language.
Could you give me an example to do it?

**Comment by DesarrolloIT-LM** [comment]
**This is my code using a Zebra Printer ZQ310.
Ionic: 6.17.1 (capacitor)
Testing on Android Device (android 10)**



`import { BluetoothSerial } from '@ionic-native/bluetooth-serial/ngx';


constructor(
	private blueTooth: BluetoothSerial,
) {}


setConnect() {
	this.blueTooth.connect('printer address').subscribe(c => {
	  if (c) {
	  	this.writeZebra();
	  }
	}, e => { reject(`ERR_CONNECT: ${e}`); });	
}



writeZebra() {
	let cmd: string;

    cmd += `! U1 SETBOLD 1\r\n`;
    cmd += `! U1 SETLP 7 1 48\r\n`;
    cmd += `BLA BLA BLA BLA BLA BLA BLA\r\n`;
    cmd += `! U1 SETBOLD 0\r\n`;
    cmd += `! U1 SETLP 7 0 9\r\n`;
    cmd += `BLA BLA BLA BLA BLA BLA BLA\r\n`;
    cmd += `BLA BLA BLA BLA BLA BLA BLA\r\n`;
    cmd += `BLA BLA BLA BLA BLA BLA BLA\r\n`;
    cmd += `\r\n`;
    cmd += `BLA BLA BLA BLA BLA BLA BLA\r\n`;
    cmd += `BLA BLA BLA BLA BLA BLA BLA\r\n`;
    cmd += `\r\n\r\n`;
    cmd += `! U1 BARCODE 128 1 1 60 0 20 982021072\r\n`;
    cmd += `\r\n\r\n`;
    cmd += `\r\n\r\n`;

	this.blueTooth.write(cmd).then(res => {
	  if (res) {
	    console.log('PRINT TEST OK');
	  }
	}, e => {
	  console.log(e);
	});
}
`

I hope this help you.
regards!

**Comment by DesarrolloIT-LM** [comment]
the commands are there: https://support.zebra.com/cpws/docs/comtec/PROMAN-CPCL_RevY.pdf
