### ISSUE TITLE
How to print Image ?

### ISSUE THREAD

**Issue by sahilmo** [razmans/ionicBluetoothPrint#6]
How to print logo image in pos thermal receipt printer? I printed string that is worling good. I want to print logo?

**Comment by boubacar2** [comment]
Hi,
Thx you very much for your job. But i want print QRCode  and HTML content  in pos thermal 
Do you know how i can do that ?
Thx

**Comment by razmans** [comment]
Sorry, I have not figured out how to print QR code and logo image.

**Comment by alejandrojcc** [comment]
Hi! @sahilmo @boubacar2 Could they print the qr code? Thanks!

**Comment by IamSurendraThota** [comment]
hi did found the way to print image ?
