### ISSUE TITLE
Print QRCode

### ISSUE THREAD

**Issue by boubacar2** [razmans/ionicBluetoothPrint#7]
Hi,
Thx you very much for your job. But i want print QRCode and HTML content in pos thermal
Do you know how i can do that ?
Thx

**Comment by razmans** [comment]
You should be able to print plain text, regarding HTML content, just push the HTML text into the buffer

Sorry, I have not figured how to print QR Code or images yet.

**Comment by boubacar2** [comment]
Thx for your answer.
Push the text html in the buffer? I can not do it. Can you give me a little example so that I can understand the process, please?
