### ISSUE TITLE
Can't print Chinese word

### ISSUE THREAD

**Issue by uokivan** [razmans/ionicBluetoothPrint#8]
Thanks very much, I can print English and numbers,
but can't print Chinese word...., such as "謝謝",
how to fix it ?
Thanks a lot

**Comment by SirukakSosta** [comment]
Hi you can always encode your text with iconv or iconv lite.

Check this gist
https://gist.github.com/SirukakSosta/1e0ba916737926ab2f64b8f194f75a56

Please try all the available formats to see if anything fits you.
Chinese
    EUC-CN, HZ, GBK, CP936, GB18030, EUC-TW, BIG5, CP950, BIG5-HKSCS,
    BIG5-HKSCS:2004, BIG5-HKSCS:2001, BIG5-HKSCS:1999, ISO-2022-CN,
    ISO-2022-CN-EXT, BIG5-2003 (experimental)

**Comment by uokivan** [comment]
> Hi you can always encode your text with iconv or iconv lite.
> 
> Check this gist
> https://gist.github.com/SirukakSosta/1e0ba916737926ab2f64b8f194f75a56
> 
> Please try all the available formats to see if anything fits you.
> Chinese
> EUC-CN, HZ, GBK, CP936, GB18030, EUC-TW, BIG5, CP950, BIG5-HKSCS,
> BIG5-HKSCS:2004, BIG5-HKSCS:2001, BIG5-HKSCS:1999, ISO-2022-CN,
> ISO-2022-CN-EXT, BIG5-2003 (experimental)

Dear @SirukakSosta 
Thanks a lot

**Comment by akmelalee** [comment]
how to use this file ? please guide !!!!!!!!!


..
..
import * as iconv from 'iconv-lite';
..
..
let encodedWord = iconv.encode('謝謝', 'EUC-CN');
